service: otp-co2
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  plan:
    handler: handler.plan
    events:
      - httpApi:
          method: GET
          path: /plan

plugins:
  - serverless-esbuild
  - serverless-offline